### ISSUE TITLE
Exclude private IP addresses

### ISSUE THREAD

**Issue by nmalcolm** [honoki/bbrf-client#103]
When running `bbrf domains --view resolved` it includes subdomains which resolve to private IP space. This can be undesirable when working with third party tools because running httpx, etc. on these subdomains is pointless (assuming you have fresh DNS records and you're not working with stale data) and wastes a lot of time and resources.

Additionally we can have false positives. If foo.example.com points to 172.17.0.1, `bbrf domains --view resolved | httpx` will show foo.example.com as alive, but that's our own couchdb server. A simple --exclude-private flag would help greatly for times where working with truly internal subdomains doesn't make sense.

**Comment by honoki** [comment]
Hi @nmalcolm - I agree that this would be a nice feature to have. I have been facing similar use cases while using bbrf.

This can probably be achieved by building an additional server view (e.g. `domains_resolved_exclude_private` in CouchDB with something like:

```javascript
function (doc) {
  if(doc.type == "domain" && doc.ips.length > 0)
    for(ip in doc.ips)
        if(isPrivateIP(ip)) return;
    emit(doc.program, doc._id);
}
```

The alternative approach would be to write a filter function on the bbrf-client, which would put the load on the client and therefore probably be less interesting. I'm looking into these options.

**Comment by honoki** [comment]
Some initial tests on my local installation seem to point to this working:

```javascript
function (doc) {
  if(doc.type == "domain" && doc.ips.length > 0) {
    for(ip in doc.ips) {
      var i = doc.ips[ip].split(".");
      if(i[0] != "10" && !(i[0] == "192" && i[1] == "168") && !(i[0] === '172' && (parseInt(i[1], 10) >= 16 && i(parts[1], 10) <= 31)) )
         emit(doc.program, doc._id);
    }
  }
}
```
I will write some tests and add a flag `--no-private` in the next push of the client.
