### ISSUE TITLE
Allow tags on parameters

### ISSUE THREAD

**Issue by nullenc0de** [honoki/bbrf-client#105]
In some cases it's helpful to tag parameters. For this example, it would be good to tag the full GET request, as the parameter is interesting and may suggest investigation.

`bbrf urls -q |gf xss |bbrf url -q add - -t interestingparam:true`

If you `bbrf tags interestingparam` you will see the endpoint without the parameter.

**Comment by honoki** [comment]
Hello - apologies for the delayed response. Can you explain in more detail what you're trying to do and why it doesn't work today? From what I can see, this command should work: `bbrf url add - -t interestingparam:true`.
