### ISSUE TITLE
Feature request: add custom properties to documents

### ISSUE THREAD

**Issue by honoki** [honoki/bbrf-client#11]
By supporting custom properties to be set for documents, you could specify e.g. the platform a program belongs to or the name of a team member that added a bunch of new domains.

This could look as follows:

```bash
bbrf new example --set platform:intigriti
bbrf domain add 'www.example.com' --set added_by:pieter 'comment:just stumbled across this'
```

This probably requires some checks on property names to ensure the integrity of the information, e.g. no reserved keywords like `id`, `_id`, `_rev` or bbrf-related fields like `domains`, `ips`, `url`, `type`, etc. should be allowed.

**Comment by 0xJeti** [comment]
Great idea, this will make bbrf very extensible!
Maybe it will be easier to prefix internally all custom fields (e.g `added_by` will become `x_added_by` which theoretically should fix the problem of name collisions.

**Comment by BitThr3at** [comment]
this would be superb, let me know if I could help...

**Comment by honoki** [comment]
Working on this at the moment. Currently have this implemented (but not yet merged):

Add tags to documents by using a `-t key:value` when creating a new domain, ip or url:

```bash
cat domains.txt | bbrf domain add - -t added_by:pieter -t from:domains.txt
bbrf ip add 1.2.3.4 -t added_by:pieter
```

Then search documents with the new `search` command:

```bash
bbrf search added_by pieter
bbrf search added_by pieter ip # specify the doctype (ip, domain, url) to limit your search
bbrf search from domains.txt -p test # specify a program to limit your search
```

To support this, all tags are stored in a new `tags` property on the document, and a new view `search_tags` is defined on the database that spits out all custom tags:

```js
function (doc) {
  if(doc.tags) {
    for(prop in doc.tags) {
      emit([prop, doc.tags[prop]], [doc.type, doc._id])
    }
  }
}
```
Removing tags can be achieved by setting an empty value:

```
bbrf update 1.2.3.4 -t added_by:
```

What I'm still contemplating is:
- whether/how to support custom tags on documents that aren't ips, domains or urls (i.e. programs)

**Comment by honoki** [comment]
I received some feedback from @0xJeti about the proposed solution:

He has a suggestion to use the existing commands rather than a new `search` command, e.g.:
```
bbrf ips -t added_by:pieter
```
I agree that this has more virtue to it, but the downside of this approach is that no "universal" search (across ips, domains and urls together) can exist; I'm not sure if that's actually a problem. The upside: this could allow combinations of e.g. `--view resolved` and `-t key:value` flags to apply the search to a subset of the documents only. Although that in itself brings some extra challenges with regard to performance.

Another remark is that this proposition is a text-based approach, and that it could be very useful to have e.g. dates stored in the tags to allow storing information like `last_updated` or `last_scanned`. This logic is feasible using the couchdb backend, but would require some more features in the bbrf client in order to query data since/before a certain timestamp.

I'll give this a bit more thought before I push my current implementation. :)

**Comment by honoki** [comment]
OK, I think found a way to reconcile all of the above by adding the subcommand `where` which accepts the following syntax:

```bash
bbrf domains where <tag_name> is [before | after] <value> [(-p <program> | --all)]

# for example
bbrf domains where added_by is pieter --all
bbrf domains where last_updated is before 1610698911
bbrf domains where last_scan is after 2021-01-01 -p myprogram
```

This works on `domains`, `ips` and `urls` and will query custom tags based on text-based comparisons as is defined in the [Unicode Collation Algorithm](https://unicode.org/reports/tr10/) as [implemented by Couchdb](https://docs.couchdb.org/en/latest/ddocs/views/collation.html#collation-specification).

Since all values are stored as text, this allows date comparison if you store dates as unix timestamps or in a ISO-8601 format e.g. `2021-01-15T09:02:40.628Z`.

That also means, however, that for example `"20"` comes after `"1000"`, which makes this less suitable for integer comparison. So if you want to store integers, you may want to use padded zeros at the front to ensure that `0020` comes before `1000`.
