### ISSUE TITLE
SSL Error

### ISSUE THREAD

**Issue by issaclutch007** [honoki/bbrf-client#110]
Hey I've followed all the steps correctly after setting up a new vps and creating a subdomain for example: bbrf.example.com to host the server configured the server hosted it properly verified it after visiting the website, setup ssl properly now when i try to run `bbrf new target` it gives out the following error and I am unable to comprehend what it is about:
```
[ERROR] HTTPSConnectionPool(host='bbrf.example.com', port=443): Max retries exceeded with url: /bbrf/target (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))
```

I'll be highly obliged if i can get an answer about it.

**Comment by honoki** [comment]
Can you show the result of `curl https://bbrf.example.com/bbrf/target`?

In general, you can bypass certificate errors by setting `{"ignore_ssl_errors": true}` in the `~/.bbrf/config.json` file.
