### ISSUE TITLE
Hooks Not working

### ISSUE THREAD

**Issue by sahadev0079** [honoki/bbrf-client#112]
I did bbrf listen, I have added all the hooks in the correct folder and made them executable too. 

![image](https://github.com/honoki/bbrf-client/assets/111126595/1a62a86c-f41f-4f05-b4af-3b419e1ed861)
getting this error.

**Comment by honoki** [comment]
It appears that there is an issue connecting to your BBRF server rather than the hooks not working; this may be worth investigating if you can reproduce this behavior. Let me know if this persists, and we can track this problem.
