### ISSUE TITLE
 add_documents gets called even if add_domains is empty

### ISSUE THREAD

**Issue by thejeshgn** [honoki/bbrf-client#20]
Try adding an out of scope domain.
in line  https://github.com/honoki/bbrf-client/blob/master/bbrf.py#L246
`add_documents` gets called with empty `add_domain` object. Wasted call.

**Comment by honoki** [comment]
Calls are free, though! :) Thanks for the feedback, but I do not consider this a bug. I believe there are more/other opportunities to improve the performance of the client, one of which would be to move from python to something faster (rust/go).

**Comment by honoki** [comment]
I've been revisiting some code, and now understand that you meant an HTTP request rather than a function call! I'm planning to remove this kind of overhead in an upcoming version, by always reducing the number of unnecessary calls to a minimum.

Thanks again for this feedback!

**Comment by honoki** [comment]
This has been fixed in v1.1.1, along with some other unnecessary calls.
