### ISSUE TITLE
add_domains doesn't add any value to database

### ISSUE THREAD

**Issue by idlwngdd** [honoki/bbrf-client#22]
I can add program, inscope, out scope, but I can't add domain to the program.
`> bbrf show starbucks`
`{"_id":"starbucks","_rev":"2-6e239c74c5dc4d17055ab4cbe087c18d","type":"program","disabled":false,"passive_only":false,"inscope":["www.starbucks.com"],"outscope":[]}`

When I type : 
`> bbrf domain add 1.starbucks.com -p starbucks`
and then:
`> bbrf domains`
its output is none.

**Comment by honoki** [comment]
Hi @idlwngdd - the example you gave works as expected. `1.starbucks.com` does not match the inscope `www.starbucks.com`. If you want it to be added, make sure you add `*.starbucks.com` to the inscope.

If you're unsure how the scope definitions are used, have a look at [the definition of `matches_scope` here](https://github.com/honoki/bbrf-client/blob/7ce0a4144598dba54438161978e3a6220fea27e8/bbrf.py#L110).
