### ISSUE TITLE
ImportError: attempted relative import with no known parent package

### ISSUE THREAD

**Issue by pdelteil** [honoki/bbrf-client#28]
```
python3 bbrf.py 
Traceback (most recent call last):
  File "/home/kali/software/bbrf-client/bbrf/bbrf.py", line 48, in <module>
    from . import bbrf_api
ImportError: attempted relative import with no known parent package
```

After a fresh install. A workaround is removing "from ."

**Comment by honoki** [comment]
Hi @pdelteil - have you installed with `pip install bbrf`? If so you shouldn't have to try running `python3 bbrf.py` anymore, but you can just run `bbrf` as a standalone command from the command line.

If you had a previous version of BBRF client installed, make sure you remove the bash function that it needed from your `.bash_profile` or `.functions` (or wherever you defined it) first! Once the function is removed, open a new terminal and the command `bbrf` should work.

**Comment by honoki** [comment]
We discussed this via Twitter and this issue was resolved.

**Comment by pdelteil** [comment]
Thanks.
