### ISSUE TITLE
Unexpected behaviour adding domains when scope is only *.example.com

### ISSUE THREAD

**Issue by rsilvav** [honoki/bbrf-client#36]
When starting with a new program and defining scope only with:

bbrf scope in add *.example.com

trying to add the domain example.com will fail.

For replying the behaviour try:

bbrf new example
bbrf use example
bbrf inscope add *.example.com
bbrf domain add example.com
bbrf domains

Output will be empty.

**Comment by anasbousselham** [comment]
Hi,
Your bbrf server is up!?

**Comment by honoki** [comment]
Hi @rsilvav - this is expected behaviour. BBRF at the moment does not match `example.com` to `*.example.com`, as it doesn't consider it a strict subdomain.

So I would recommend adding `example.com` as in scope explicitly.

I have some ideas about changing the default behaviour, but nothing concretely planned.

**Comment by rsilvav** [comment]
Checking the matches_scope function i noticed that this specific flow avoids both literal and x.example.com matches. An user can avoid this behaviour by "forcing" the exact match adding always example.com to the scope, but in my opinion, this isn't intuitive.

An additional checking like the following could avoid this behaviour:

if s.startswith('*.'):
    if domain.endswith('.'+s[2:]) or s[2:]== domain:
        return True

**Comment by rsilvav** [comment]
@honoki thanks for your answer! 

Strictly speaking you're right, but programs with wide scope (like *.example.com) usually are implicitely including example.com (maybe they are wrong?)

It is an ambiguous, but in my opinion is better to send some out-of-scope reports than missing some implicitely-valid bugs. Maybe inverting  the  behaviour (example.com matches *.example.com unless example.com is out-of-scope) is an alternative.

For now i will follow your advice :)
