### ISSUE TITLE
Filter urls/domains/ips by source

### ISSUE THREAD

**Issue by pdelteil** [honoki/bbrf-client#38]
Hi @honoki,

I'm not sure if this feature maybe in your dev plans. So far I haven't found a way to query the data by source value.
I'm expecting something like this:

``` 
> bbrf urls where source is 'httpx' 
```

**OR** 
```
> bbrf urls -s 'httpx' 

```

**Comment by honoki** [comment]
Hi @pdelteil - this is supported in recent versions of the BBRF server. To make it available on your server, you need to push the updated `views.json` to the server:

```bash
wget https://raw.githubusercontent.com/honoki/bbrf-server/main/views.json
curl -X PUT $COUCHDB"bbrf/_design/bbrf" \
     -u admin:password \
     -H "Content-Type: application/json" \
     -d @views.json
```

Do note that this will cause your server to be unavailable for a few minutes while it rebuilds the view indexes.

**Comment by pdelteil** [comment]
Thanks a lot. I was not following the updates of the bbrf-server, I will keep an eye on it.
