### ISSUE TITLE
Feature request: Search

### ISSUE THREAD

**Issue by pdelteil** [honoki/bbrf-client#39]
Sometimes I would like to know the program from which a domain is coming from, for example, somedomain.com 

`` bbrf search domain somedomain.com  ``

**Output**

 ``>  _Program ``

Search IP

``bbrf search ip 1.1.1.1 ``

**Output** 

``> Program0
  Program1 
...
 Program n  ``

Search URL 

`` bbrf search http://www.test.com``

**Output** 
`` >  Program_0 ``

**Comment by honoki** [comment]
While there is no command for that specifically, you can achieve this by viewing the JSON document as follows:

```
bbrf show subdomain.com
# parse the program with jq:
bbrf show subdomain.com | jq -r .program
```

This works because every ip and domain in your database are a separate document with the up/domain as the unique identifier.

**Comment by pdelteil** [comment]
Works pretty well. 

Thanks.
