### ISSUE TITLE
Feature Request : Site Title and Webserver

### ISSUE THREAD

**Issue by z0mb13s3c** [honoki/bbrf-client#40]
First off, thanks so much for this awesome tool. Got txt files everywhere and this is a total lifesaver. Just started using it after watching you on Nahamcon.

At the moment URLs support status code and content length but it would be amazing to have the ability to pipe domains into httpx and store the site title, webserver and content type too. That way you can just query for any url that had XYZ in the title or Apache in the webserver.

Example httpx output:
http://sub.domain.com:80 [200] [178] [text/html] [I'm the title] [nginx]

Example command:
bbrf urls where title is "I'm the title"
bbrf urls where webserver is "nginx"

Again, thanks a million for this tool.

**Comment by z0mb13s3c** [comment]
In the hopes to try an help out a bit, I've tried to keep the output of httpx to space separated (as is currently supported)
echo "example.com" | httpx -content-length -content-type -status-code -title -web-server -no-color -H "User-Agent: Mozilla" | sed 's/[][]//g'
Returns :
https://example.com 200 1256 text/html Example Domain ECS (dcb/7FA6)

As you can see, the title has a space in it which would probably pose some problems.

Alternatively, httpx can return a json output which could potentially be parsed (the json output has everything that it found, without the need to specify all those flags.

echo "example.com" | ./httpx -json

**Comment by honoki** [comment]
Hi @z0mb13s3c - thanks so much for your appreciative words and for your good suggestion.

The first thought that comes to mind is that what you're asking can be (partially?) achieved using the custom tags, e.g. you should be able to do:

```bash
[...] | bbrf url add - -t 'title:$title' -t 'web-server:$server'
```

This implies that you should temporarily store the title and server in variables or use `xargs` to pass as additional arguments, but I would encourage you to find a solution that uses the tagging system and let me know if you come across any issues doing that. It will also allow you to do exactly what you asked:

```
bbrf urls where server is nginx
bbrf urls where title is WebApp
```

If there are shortcomings to this solution, please let me know here and I will consider adding it as a "real" option instead.

**Comment by z0mb13s3c** [comment]
Thank you very much for your reply. Not a bad idea at all. With tags you can query and store any info you want. I will give it a go and try to cook something up and let you know the outcome. 

Thanks again

**Comment by z0mb13s3c** [comment]
So.... I came up with this little tool which comes with a warning haha. I'm not the best coder and hopefully someone more experienced than me can help clean this up...but it works.

https://github.com/z0mb13s3c/httpx2bbrf

I tested it with a list of 4000 domains out of which 447 where live and properly added them to BBRF. All it's doing is grabbing HTTPX's json output, parses it, puts the required data into variables, constructs the full command and executes a bbrf url add in the shell. It seems to be working. There was a title with Chinese characters and it added it without any problems.

Note: I did do a bbrf use program before hand. I'm not sure if bbrf adds the urls automatically to the correct program based on the domain or you have to do a bbrf use program beforehand.

If you happen to test it. Let me know what you think.

Thanks again for this absolute lifesaver of a tool! :)

**Comment by 0xtavian** [comment]
Big thank you to both of you. I love BBRF and @z0mb13s3c tool really highlights the possibilities imo. On top of chained queries what about regex queries and partial matches? It would be pretty great to see BBRF able to store meg https://github.com/tomnomnom/meg data aka http response data and grep for regex matches. Just my two cents. thanks again for the amazing tool @honoki ! <3

**Comment by z0mb13s3c** [comment]
So, after some more testing and digging around (correct me if i'm wrong), i noticed two main issues with the tagging system:

1) multiple tags with the same name
2) the querying of the tags

Let me give a concrete example. HTTPX spits out cnames, which can be multiple. As it stands, passing the same tag overwrites the previous one.

Ideally, the tagging system would be nested. For example,

```
"cnames": [
    "cname1",
    "cname2",
    "cname3"
  ],
  ```
  
That way, you query the cname parent and looks for your query in its list of values. That would fix both issues. I think the ip's in domain view already does this.

Let me know what you think.
Z.

**Comment by honoki** [comment]
Hi @z0mb13s3c - I follow your logic, but am not sure that both things can be easily achieved with CouchDB. I'll write up some of my thought process below to hopefully come to a conclusion.

### Storing tags as arrays

This is likely feasible but would complicate the logic of removing and updating tags. It would require some additional syntax to indicate the wanted behaviour from the command line. 

At the moment, the syntax is simple: `-t name:value` will add the tag if it doesn't exist, or replace it when it does. And `-t name:` will remove the tag from the document.

One question that would need to be answered to support array-based tags, is how should BBRF handle the following:
```bash
bbrf domain update example.tld -t cname:cname1
bbrf domain update example.tld -t cname:cname2
```

Should the document replace the second cname value or append it? And if it should be appended, what syntax could be used to overwrite it with the second? As an example, running `bbrf update example.tld -t timestamp:$(date +%s)` would always expect the `timestamp` tag to be updated, not appended.

A potential solution may be to have an option `--append-tags` to force all tags to be stored as an array and append the values, instead of overwriting the old value:

```bash
bbrf domain update example.tld -t cname:cname1
bbrf domain update example.tld -t cname:cname2 --append-tags # should result in cname being an array
bbrf domain add example.tld -t some:value1 -t some:value2 --append-tags # should result in some being an array
```

From the server-side, this would require changes to the tags view to ensure all elements in an array are pushed to the index, which is feasible.

### Using wildcards in queries

This one I believe cannot be achieved with the architecture of the BBRF server as it exists today, as it is a limitation of CouchDB to only support string range searches, i.e. we can query data between startkey="a" and endkey="ab" to return all data starting with `aa`, but wildcards are not supported by default.

Seel also this question: https://stackoverflow.com/questions/5509911/how-do-i-create-a-like-filter-view-in-couchdb

This means it would require significant changes to the architecture to make this possible, which is not something I plan to do on the short term. As an alternative approach, I believe there may be value in making it possible to dump all values for a specific tag, e.g. `bbrf tags cname` to get a list of all cname values in the database and the document they belong to, which can then be searched using grep.

This would be a fairly straightforward change, which makes me like it more as a solution. :)

Would like to hear your feedback on this!

**Comment by z0mb13s3c** [comment]
Hello Honoki :)

**Wildcard in Queries**

Dumping all values of a tag is a very good solution to be honest. I don't think anyone would mind doing a simple grep. If this would be the case, the output can maybe be delimited. Taking the webserver tag as an example

`bbrf urls tag webserver`

"Microsoft-IIS/10.0" https://hello.domain.tld
"JSP3/2.0.14" https://bye.domain.tld

This way one can simply do something like :
`bbrf urls tag webserver | grep -i "soft" (or chaining multiple greps) | awk '{print $2}'`
`bbrf urls tag webserver | grep -i "soft" (or chaining multiple greps) | awk '{print $2}' | unfurl domain`

The only issue that I see, if it's not a single line output. For example, at the moment, with my tool, I can store the server response too, which is multi-line. The output would be horrific to parse in a sensible way. The only thing that comes to mind is maybe add a --json parameter to `bbf urls tag webserver --json` and one can do some Grep+JQ magic. Granted, it would result in a way longer "one-liner" but that can always be sorted with an alias or something.

**Tags as Arrays**
I like the proposed solution as well, with the --append-tag. To avoid double records, the --append-tag could maybe have a little check before it appends. If the value already exists in the tag array, ignore the command. Without the --append-tag, behaviour remains the same as is today. To update/remove in a tag array, the syntax might be sort of a query. For example:

`bbrf url tagupdate -u "https://hello.domain.tld" -t webserver -old "Microsoft-IIS/10.0" -new "Apache"`
`bbrf url tagremove -u "https://hello.domain.tld" -t webserver -value "Microsoft-IIS/10.0"`

The first command would look for "Microsoft-IIS/10.0" as a value in the webserver tag array. If the tag is not an array, maybe return an error to the user "Tag [webserver] for [https://hello.domain.tld] is not a tag array. Use bbrf url add [URL] -t tag:value instead"

I think having both of the above functionalities would extend the use of BBRF to a limitless amount as you can potentially store "anything" in tags. List of endpoints, a list of filenames which where found through file/dir fuzzing etc.

Let me know what you think.

**Comment by 0xtavian** [comment]
@honoki

To your question "Should the document replace the second cname value or append it?" I think the answer is to replace it.

I image limiting the amount of nested arrays to one.

 command like this

bbrf domain update example.tld -t cname:cname1
bbrf domain update example.tld -tt cname:cname2 
bbrf domain update example.tld -ttt cname:cname3 

would produce a structure __like_  this _maybe_


```
"cname": [
    "cname":"cname1",
    "cname":"cname2",
    "cname":"cname2",

  ],
```
To replace cname2 run

bbrf domain update example.tld -tt cname:newvalue

```
"cname": [
    "cname":"cname1",
    "cname":"newvalue",
    "cname":"cname2",

  ],
```

to delete the entire array `bbrf domain update example.tld -t cname:` or maybe `bbrf domain update example.tld -tt cname:[2]` to only delete the second key-value pair, in the above case it would delete `newvalue`.

```
"cname": [
    "cname":"cname1",
    "cname":"cname2",
  ],
```

love your work. thank you so much.
​

**Comment by honoki** [comment]
I've spent some time on these two features today, and I believe I've got a working candidate to push to the next release.

### Greppable tags

```bash
bbrf tags # returns a list of all your custom tag names
bbrf tags tagname # returns a space-separated list (<id> <value>) of documents that have <value> for your <tagname>
```

I haven't looked into multiline support here yet, but let me know if you have some good examples of multiline data that wouldn't work with this method.

### Tags as arrays

I avoided additional subcommands like `tagupdate` or `tagremove`, but have gone for the following set of rules:
* if a single `-t tag:value` is found, treat as a normal value;
* if the same tag name is provided more than once, default to an array: `-t cname:one -t cname:two`
* by default, overwrite existing values for the tags when updating, unless `--append-tags` is specified, in which case append new values to existing values:

```bash
bbrf domain update www.example.tld -t name:value
bbrf show www.example.tld | jq .tags # { "name": "value" }
bbrf domain update www.example.tld -t name:value2 -t name:value3
bbrf show www.example.tld | jq .tags # { "name": ["value2", "value3"] }
bbrf domain update www.example.tld -t name:value4 --append-tags
bbrf show www.example.tld | jq .tags # { "name": ["value2", "value3", "value4"] }
bbrf domain update www.example.tld -t name:
bbrf show www.example.tld | jq .tags # { }
```

The updates required at the BBRF server are also ready to be pushed when this release is published.

I'm going to continue running some tests against this, but plan to push a new release with these features over the next few days.

**Comment by z0mb13s3c** [comment]
Hello :)

Wow! The above sounds really exciting. I'll definitely test it out and report back. A good example of multiline data would be the server response output from httpx. At the moment, my tool converts and stores it as \r\n which i guess would make it technically as single line? Also, I think there's some sort of character limit per line, as the following example was cut short at the end. I'm not sure if this is a problem with my tool or a limitation with bbrf, couchdb or anythere else.

```
HTTP/1.1 403 Forbidden
Connection: close
Content-Length: 915
Content-Type: text/html
Date: Thu, 18 Mar 2021 20:20:08 GMT
Server: CloudFront
X-Cache: Error from cloudfront

<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">
<HTML><HEAD><META HTTP-EQUIV=\"Content-Type\" CONTENT=\"text/html; charset=iso-8859-1\">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>403 ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size=\"1px\">
Bad request.We cant
```

Looking forward to this release and thanks again for spending the time on it. You're making recon organised and my pc (and my sanity) adores you for it haha!

**Comment by honoki** [comment]
v1.1.1 has been released, let me know how it works for you!
