### ISSUE TITLE
Feature request: Get all urls with query parameters

### ISSUE THREAD

**Issue by tume70** [honoki/bbrf-client#42]
Hello! Thanks for the awesome tool, you guys have done a great job so far! 

I think it would be great if one can query all urls with query parameters so its possible to feed them to another tool (think dalfox / sqlmap). At the moment the parameters are not returned when querying all urls:
`bbrf urls`

Since its storing the parameter values in array:
`bbrf show https://hostwithqueryparams.xyz`

`{
  ...
  "hostname": "hostwithqueryparams.xyz",
  "port": 443,
  "status": 200,
  "content_length": 298820,
  "query": [
    "cat=1&catb=136",
    "product=4847"
  ]
  ...
`

The syntax could be:
`bbrf urls -params`

Which returns all urls with query parameters:
`https://hostwithqueryparams.xyz?cat=1&catb=136`
`https://hostwithqueryparams.xyz?product=4847`
`...`

Thanks! :)

**Comment by honoki** [comment]
This was a good idea, I implemented it in v1.1.1. Thanks for the suggestion!

**Comment by honoki** [comment]
This should now work as expected.
