### ISSUE TITLE
urls cannot be matched by port number

### ISSUE THREAD

**Issue by tume70** [honoki/bbrf-client#43]
Hi! Thanks for the new release!  Really great job, again!

To the point... I don't know if I have this problem locally or not, but when trying to query all urls with certain port number with command like:
`bbrf urls where port is 443`, the command does not result any urls despite the fact that I most certainly have urls with port 443:
`bbrf show https://test.xyz`
`..."hostname":"test.xyz","port":443, ...`

However when trying to query with source or custom tag(s), it works flawlessly. Thanks again :)

**Comment by honoki** [comment]
This will be incorporated in the next release. Thanks for your feedback!
