### ISSUE TITLE
[Feature request] Verbose/debug flag 

### ISSUE THREAD

**Issue by pdelteil** [honoki/bbrf-client#45]
Sometimes I face errors like this one 

``Hostname could not be parsed, skipping http:// ``  

I have no idea what the _hostname_ is or what might have cause the error. 

I would be useful to increase the verbose level to show what hostname was giving troubles.

**Comment by honoki** [comment]
Hi - you can add a `"debug":true` to you `config.json` for some basic verbose error messages. 

The missing hostage error likely stems from an empty line at the end of your input, which it prepends with `http://` before trying to process. 

I'll add a check to purge empty lines from input.

**Comment by pdelteil** [comment]
> Hi - you can add a `"debug":true` to you `config.json` for some basic verbose error messages.
> 
> The missing hostname error likely stems from an empty line at the end of your input, which it prepends with `http://` before trying to process.
> 
> I'll add a check to purge empty lines from input.

Thanks, I will give it a try!

**Comment by pdelteil** [comment]
> Hi - you can add a `"debug":true` to you `config.json` for some basic verbose error messages.
> 
> The missing hostname error likely stems from an empty line at the end of your input, which it prepends with `http://` before trying to process.
> 
> I'll add a check to purge empty lines from input.

I think I would be simpler and easier to use a flag instead a config file. :D

**Comment by honoki** [comment]
I agree, but the use of docopt to generate the documentation and supported flags sadly doesn't allow me to specify global flags without cluttering each of the documentation lines with a `[--debug]` option.

So closing for now, until somebody can suggest a way around that.
