### ISSUE TITLE
Feature: Search by keyword

### ISSUE THREAD

**Issue by plenumlab** [honoki/bbrf-client#5]
Ability to search db by keywords
example:

```
> bbrf domains -p vzm -s omega
something.omega.gq1.yahoo.com
omega.gq1.yahoo.com
gq1.something.omega.yahoo.com
```

**Comment by honoki** [comment]
Closing this for now as I don't plan to implement this. I would recommend just using grep to do this, until I can think of a use case where a built-in filter is more appropriate.

**Comment by honoki** [comment]
Note that this is now partially supported by the custom tagging system and querying syntax:

```bash
bbrf services where port is 4443
```
