### ISSUE TITLE
Collision handling

### ISSUE THREAD

**Issue by rsilvav** [honoki/bbrf-client#50]
Hello,

I've been using bbrf and i have the following situation:

- *.example.com is **in** scope
- www.example.com is **out** of scope

What do will bbrf do in this particular case? is outscope "stronger" than in? In my particular case i filled inscope of several programs automatically, then i checked for example.com program and filled out of scope after adding www.example.com as a valid domain and url. Then when added www.example.com to out of scope, bbrf kept showing www.example.com when using bbrf urls.

If this is intended behaviour, could bbrf outscope add remove both domains and urls?

Thanks in advance

**Comment by rsilvav** [comment]
Yes, thank you for your answer!

Just as an observation, after executing the above commandline, i've managed to remove the URL by:

`bbrf scope out | httpx -silent | bbrf url remove -`

Next time, if any, i will start by removing urls, lol

**Comment by pdelteil** [comment]
> Yes, thank you for your answer!
> 
> Just as an observation, after executing the above commandline, i've managed to remove the URL by:
> 
> `bbrf scope out | httpx -silent | bbrf url remove -`
> 
> Next time, if any, i will start by removing urls, lol

I think I would be better to run it like this:

``bbrf scope out  | subfinder -silent | httpx -silent |  bbrf url remove - ``
