### ISSUE TITLE
[Issue] debug false doesn't work in config file

### ISSUE THREAD

**Issue by pdelteil** [honoki/bbrf-client#54]
I was using the option ``"debug": "true"`` changed it to ``"debug": "false"`` but still shows the debug message. 

Thanks.

**Comment by 0xJeti** [comment]
Hi @pdelteil.
How is it working with `"debug":false` (no double-quotes around `false`) ?

**Comment by pdelteil** [comment]
> Hi @pdelteil.
> How is it working with `"debug":false` (no double-quotes around `false`) ?

Hello @0xJeti,

Without quotes it works as intended. 

Which is inconsistent with other flags such as "ignore_ssl_errors":"true", if it's a boolean shouldn't have quotes.

**Comment by honoki** [comment]
This is a good point, it looks like "false" gets loaded as a non-empty string in Python, which evaluates to True rather than False. Will fix the documentation to be aligned.

**Comment by pdelteil** [comment]
> This is a good point, it looks like "false" gets loaded as a non-empty string in Python, which evaluates to True rather than False. Will fix the documentation to be aligned.
> 
> EDIT - the documentation already says `"ignore_ssl_errors": true` (without quotes). Did you find it with quotes elsewhere?

To be honest, I don't remember. Probably my bad.
