### ISSUE TITLE
[issue] Problem using symbol in program name

### ISSUE THREAD

**Issue by pdelteil** [honoki/bbrf-client#55]
Hi @honoki, 

A collaborator created a program with name 'AT&T' (using `` bbrf new "AT&T"``). The program was created correctly and we could add domains, but other functions failed: 

`` bbrf use "AT&T"``  **Worked**

```
> bbrf domains
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1)
DEBUG:urllib3.connectionpool: "GET /bbrf/_design/bbrf/_view/domains?reduce=false&key=%22AT&T%22 HTTP/1.1" 400 54
[ERROR] 'rows'

> bbrf urls
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1)
DEBUG:urllib3.connectionpool: "GET /bbrf/_design/bbrf/_view/urls_by_program?reduce=false&key=%22AT&T%22 HTTP/1.1" 400 54
[ERROR] 'rows'

``` 

It would be easy for me to recreate the program without the symbol, I just wanted to point it out.

**Comment by manoelt** [comment]
It is an encode problem of  `&` when `program_name` is concatenated in the URL:

https://github.com/honoki/bbrf-client/blob/a31c4ae8eaf82229facf332922bcfbc54bc737ce/bbrf/bbrf_api.py#L64

I don't know where it would be better to encode the program name in the source code, maybe when it is being concatenated so it do not affected any other use of it.
