### ISSUE TITLE
slow processing using where source

### ISSUE THREAD

**Issue by pdelteil** [honoki/bbrf-client#56]
It takes more than a minute to execute: 

``> bbrf urls -p PROGRAM where source is 'httpx'  ``

Debug command (~ 326K urls):

```
> time curl $(jq -r .couchdb ~/.bbrf/config.json)'/_design/bbrf/_view/search_tags?key=\["source","httpx"\]' -i -u bbrf:password


 % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                Dload  Upload   Total   Spent    Left  Speed
100 22.7M    0 22.7M    0     0  3892k      0 --:--:--  0:00:05 --:--:-- 3883k

real	0m6.034s
user	0m0.315s
sys	0m0.260s

```

**Comment by honoki** [comment]
Hi @pdelteil - I'm having issues to reproduce this. Can you post output of the following commands:

```bash
time bbrf urls -p PROGRAM where source is httpx | wc -l
time curl $(jq -r .couchdb ~/.bbrf/config.json)'/_design/bbrf/_view/search_tags?key=\["source","httpx"\]' -u bbrf:password | wc -l
```

**Comment by pdelteil** [comment]
Hi @honoki, 

I'm sorry it took me so long to respond. Updated the server yesterday and it took 6 hours to rebuild. I don't know why there were several (3) compacting and indexing processes running at the same time. I have over 700k Urls and 5 MM domains. Upgraded to a bigger instance anyways. 

```
time bbrf urls -p PROGRAM where source is httpx | wc -l
3614

real	0m56.216s
user	0m12.435s
sys	0m2.255s

time curl -k $(jq -r .couchdb ~/.bbrf/config.json)'/_design/bbrf/_view/search_tags?key=\["source","httpx"\]' -u bbrf:passwordj | wc -l

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  120M    0  120M    0     0  5063k      0 --:--:--  0:00:24 --:--:-- 5321k
955384

real	0m24.474s
user	0m1.474s
sys	0m1.857s

```

**Comment by honoki** [comment]
The processing time of commands on large datasets should be drastically reduced since adding an nginx proxy in front of the the bbrf-server to allow compression, see [bbrf-server commit 6bdb695](https://github.com/honoki/bbrf-server/commit/6bdb695361cb17e923ef8e022afd1955606eb779).

**Comment by pdelteil** [comment]
Great, thanks @honoki.
