### ISSUE TITLE
[Feature request] Import inscope/outscope from Burp Suite Project Configuration file

### ISSUE THREAD

**Issue by pdelteil** [honoki/bbrf-client#57]
Hello there @honoki 

In Hackerone some programs have a ``Burp Suite Project Configuration file`` (example
[shopify.txt](https://github.com/honoki/bbrf-client/files/6340524/shopify.txt)) with the scope and outscope assests. It would be great to be able to import that file to bbrf.

**Comment by honoki** [comment]
I'm thinking that adding a specific connector for Burp Suite project config files goes against the philosophy of keeping BBRF as generic as possible. I would be more in favor of having a separate bash script that handles that, and pipe the result into BBRF.

Looking at the Shopify example, this seems to mostly do the trick (although it needs some minor tweaks):

```bash
cat /tmp/spotify | jq -r .target.scope.include[].host | tr -d '^\\$' | bbrf inscope add -
cat /tmp/spotify | jq -r .target.scope.exclude[].host | tr -d '^\\$' | bbrf outscope add -
```

This is a much more elegant solution than trying to do the same in Python :)
