### ISSUE TITLE
[issue] not able to query programs using tags

### ISSUE THREAD

**Issue by pdelteil** [honoki/bbrf-client#58]
Hello @honoki, 
I have the following program:

``` 
> bbrf show program
{"_id":"domain","_rev":"4-d573602c57707b62902e6ba77993d56f","type":"program","disabled":false,
"passive_only":false,"inscope":"*.domain.com","*.domainmoney.com","*.domainmall.com",
"*.domainbank.com","domain.com","outscope":[],"tags":{"site":"self","reward":"money"}}

```

I was trying to query programs by tag in the following way:  ``bbrf programs where site is self`` but I have no results. 

Same happens with tag _reward_ ``bbrf programs where reward is money``  I also tried using " and ' in tags names and key values.

**Comment by honoki** [comment]
Hi - it looks like I was still filtering only results (i.e. programs) matching the current program. Of course that doesn't help when you're querying other programs. I have fixed the issue and will include it in the next update.

**Comment by pdelteil** [comment]
Great. Thanks.

**Comment by pdelteil** [comment]
> Hi - it looks like I was still filtering only results (i.e. programs) matching the current program. Of course that doesn't help when you're querying other programs. I have fixed the issue and will include it in the next update.

Thanks @honoki for your work! 

I tested the fix and it works, but the result includes enabled and disabled programs (without using the flag --show-disabled) 

Greetings.
