### ISSUE TITLE
Feature: Discord alerts

### ISSUE THREAD

**Issue by nmalcolm** [honoki/bbrf-client#6]
Hi,

Really loving this tool, one feature I'd like to see is the ability to use Discord instead of Slack for alerts. This way people collaborating on Discord can have a more streamlined workflow instead of having to switch between applications.

Preferably this would be done with webhooks.

Thanks.

**Comment by honoki** [comment]
Hey @nmalcolm - this is implemented and will be included with the next release.

**Comment by honoki** [comment]
Now available in 1.1.0, see commit 0c3789d
