### ISSUE TITLE
[issue] adding domains fail due to colon

### ISSUE THREAD

**Issue by pdelteil** [honoki/bbrf-client#60]
I was adding some domains and I had this error:

[ERROR] too many values to unpack (expected 2) 

I discovered it was because of a IPv6 (therefore the `:` symbol)

Doing this solved the issue:

``cat domains.txt | grep -v ":" | bbrf domain add - -s subfinder --show-new``

**Comment by honoki** [comment]
Ah yes, BBRF doesn't currently support any ipv6 formats, so I guess this is expected to go wrong.

The error stems from trying to parse the input as `<domain>:<ip>` which is a supported format.

I will try and see if this can be resolved in a less blocking way, e.g. by ignoring malformed input rather than trying to parse it.

**Comment by pdelteil** [comment]
> Ah yes, BBRF doesn't currently support any ipv6 formats, so I guess this is expected to go wrong.
> 
> The error stems from trying to parse the input as `<domain>:<ip>` which is a supported format.
> 
> I will try and see if this can be resolved in a less blocking way, e.g. by ignoring malformed input rather than trying to parse it.

Yes, I wasn't clear that wasn't my intention to add an ipv6, just got it from subfinder/assetfinder and crashed the adding process. 

Like I said, is simple to fix adding a grep rule to filter them out, but I think that if you running an automated process of adding documents you wouldn't notice it that easy if you already have documents on that program. 

Thank you!

**Comment by Sh1Yo** [comment]
Hi, I think the same thing should be implemented for `bbrf domain update` as well. For now ipv6 works fine in `bbrf domain add` only.
