### ISSUE TITLE
Feature: Fetch entire scope

### ISSUE THREAD

**Issue by nmalcolm** [honoki/bbrf-client#7]
Currently we can do `bbrf program scope --wildcard` to fetch the domains in scope for the active program, but unless I've missed something there isn't a way to fetch all domains in scope for all programs. This makes automation difficult without looping over each domain and setting it with `bbrf use`.

**Comment by honoki** [comment]
Hey @nmalcolm - you're right, this isn't possible at the moment without iterating over all programs. I'm working and testing a solution that addresses this with the following addition to the docs: `bbrf scope (in|out) [--disabled]`

I.e. to list all scope across programs that haven't been disabled, you would run `bbrf scope in`. Similarly, a list of all outscoped domains across active programs is returned with `bbrf scope out`.

The `--disabled` flag would ony retrieve the scope of programs that are marked as disabled/inactive.

For reference, the CouchDB view to support this would look as follows:

```javascript
function (doc) {
  if(doc.type == "program") {
    if(doc.inscope.length > 0) {
      doc.inscope.forEach(function(scope) {
        emit([!doc.disabled, "IN", scope], doc._id)
      });
    }
    if(doc.outscope.length > 0) {
      doc.outscope.forEach(function(scope) {
        emit([!doc.disabled, "OUT", scope], doc._id)
      });
    }
  }
}
```

Do you think this would solve the issue you are facing?

**Comment by honoki** [comment]
Actually thought about this some more, and I believe this should be merged with the current `bbrf program scope` command as follows:

`bbrf scope (in|out) [(--wildcard [--top])] ([-p <program>] | (--all [--disabled]))`

That means all the following commands are supported:

```bash
# show in scope of current active program, replaces `bbrf program scope`:
bbrf scope in

# show out scope of current active program:
bbrf scope out

# show only wildcard domains in scope:
bbrf scope in --wildcard

# reduce wildcard domains to their "lowest common denominator", e.g. *.one.example.com and *.two.example.com would output example.com
bbrf scope in --wildcard --top

# show in scope belonging to a specific program:
bbrf scope in -p example

# show in scope across all programs:
bbrf scope in --all

# show in scope of all disabled programs:
bbrf scope in --all --disabled

# all flags enabled will show the top-level in scope domains of all disabled programs:
bbrf scope in --wildcard --top --all --disabled
```
