### ISSUE TITLE
[Feature] Telegram Notification :star: 

### ISSUE THREAD

**Issue by tequreq** [honoki/bbrf-client#75]
Hi @honoki, 

I set up bbrf-* on local machine  but it does not good work because ssl error, no sending alert discord etc.

Otherwise I think why does not option telegram? mostly we used telegram. 

thanks.

**Comment by tequreq** [comment]
Hi again @honoki, bbrf is not sending notification to discord. What can I  do?

**Comment by tequreq** [comment]
`
# Looping changes

[ERROR] ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))
`
Now I get this error.

**Comment by honoki** [comment]
Hi @tequreq - the `InvalidChunkLength` error should (hopefully) be resolved in the latest version 1.1.15. You can upgrade BBRF to try:

`pip install --upgrade bbrf`

With regards to your other questions, can yo usee if SSL errors are gone when you set add `"ignore_ssl_errors": true` to your `~/.bbrf/config.json`?

Telegram is not currently on my roadmap, but will keep it in mind if other people would find it useful.

**Comment by tequreq** [comment]
Thanks @honoki!
