### ISSUE TITLE
ERROR] HTTPSConnectionPool(host='%3cyour-bbrf-server%3e', port=443)

### ISSUE THREAD

**Issue by meetgyn** [honoki/bbrf-client#79]
bbrf  new test
[ERROR] HTTPSConnectionPool(host='%3cyour-bbrf-server%3e', port=443): Max retries exceeded with url: /bbrf/test (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f954577bb20>: Failed to establish a new connection: [Errno -2] Name or service not known'))

**Comment by pdelteil** [comment]
Your BBRF server might be down, with high load or unreachable.

**Comment by honoki** [comment]
From your error message it looks like you didn't replace `<your-bbrf-server>` in the `config.json` with your actual BBRF server. Feel free to reopen this issue if it persists.
