### ISSUE TITLE
Error when domain/scope/url has program name

### ISSUE THREAD

**Issue by pdelteil** [honoki/bbrf-client#80]
I'm having this error:

Program name: testProgram
domain: testProgramapi.domain.com

This is the output. 
```
[DEBUG] getting program blacklist
[DEBUG] REGEX_DOMAIN failed: [debug] getting program scope
```

**Comment by honoki** [comment]
Hi @pdelteil - can you please provide a set of `bbrf` commands that lead to this output? That should help me troubleshoot.

**Comment by pdelteil** [comment]
Hi @honoki,

I tried to reproduce the issue but I couldn't. I forgot what program had this issue. 

I'm closing this one, I will reopen if I find this (alleged) problem again.
