### ISSUE TITLE
Hooks not working

### ISSUE THREAD

**Issue by mortye** [honoki/bbrf-client#87]
I have added the scripts you provided in the docs/hooks/ to my ~/.bbrf/hooks directory and made them executable, when i try to add new domains or urls to my programs it's not executing.

**Comment by honoki** [comment]
Do you have a bbrf listener running somewhere? They will only be executed if that's tenue case. To start a listener, run `bbrf listen`.

**Comment by Regala** [comment]
@mortye from my experience sometimes the hooks aren't executed instantly (and they seem to be queued and a bunch are ran after sometime); but usually they do. If for some reason they don't I restart the listener like @honoki pointed via `bbrf listen`.
