### ISSUE TITLE
Discord notifications are limited to 2000 characters

### ISSUE THREAD

**Issue by 0xJeti** [honoki/bbrf-client#89]
Hi @honoki,

Another issue when dealing with large bulk additions: Discord notifications are limited to 2000 characters as per documentation: 
https://discord.com/developers/docs/resources/webhook#execute-webhook-jsonform-params

`bbrf` tries to send whole message containing a lot of information (e.g. about new domains added) in one `content` payload resulting in error on Discord API side.

I did an ugly fix for that in `bbrf_api.py` to send message in chunks:
```python
            if self.discord_webhook:               
                for i in range(0,len(message),1000):
                    chunk = message[i:i+1000]
                    requests.post(self.discord_webhook, json.dumps({'content': chunk}), headers={'Content-Type': 'application/json'})
```

**Comment by honoki** [comment]
Thanks 0xJeti! Including this in next release. :)
