### ISSUE TITLE
You need to select a program to execute this action.

### ISSUE THREAD

**Issue by pdelteil** [honoki/bbrf-client#9]
I ran one of the examples and this is my output:

```
 bbrf new vzm
 bbrf inscope add '*.yahoo.com' '*.yahoo.be'
Traceback (most recent call last):
  File "/home/ubuntu/bbrf-client/bbrf.py", line 753, in <module>
    result = bbrf.run()
  File "/home/ubuntu/bbrf-client/bbrf.py", line 667, in run
    self.add_inscope(self.arguments['<element>'])
  File "/home/ubuntu/bbrf-client/bbrf.py", line 483, in add_inscope
    (inscope, outscope) = self.api.get_program_scope(self.get_program())
  File "/home/ubuntu/bbrf-client/bbrf.py", line 126, in get_program
    raise Exception('You need to select a program to execute this action.')
Exception: You need to select a program to execute this action.
```

**Comment by honoki** [comment]
Hi - thanks for logging an issue. Can you print the contents of the file `~/.bbrf/config.json` after running the first command?

**Comment by pdelteil** [comment]
Hello there,

Sure. 

`{
"username": "REDACTED_USERNAME",
 "password": "REDACTED_PASSWORD",
"couchdb": "http://REDACTED_IP:REDACTED_PORT/bbrf",
 "slack_token": ""
}
`

**Comment by pdelteil** [comment]
It was a permissions issue, the config.json file was not writable by the standard user. 

Maybe you could include an specific error while trying to add the active program to the file and it cannot be written? 

Thank you.
