### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by KenjiMinei** [honoki/bbrf-client#94]
I installed bbrf, but whenever I try to create a new module with "bbrf new test" I get an error: "[ERROR] Expecting value: line 7 column 26 (char 258)"

![error](https://user-images.githubusercontent.com/62692574/149777581-e938e63b-8d38-45ea-88f5-304bfaaa9843.png)

**Comment by KenjiMinei** [comment]
![error2](https://user-images.githubusercontent.com/62692574/149777808-37f09539-8a13-4267-bb31-9ddbfbf292de.png)

**Comment by KenjiMinei** [comment]
![error2](https://user-images.githubusercontent.com/62692574/149777901-597bc8ee-c49b-438e-b55b-4b3824b72bb1.png)

**Comment by honoki** [comment]
Please enable `debug` in your `~/.bbrf/config.json` file and report the output of your command to help me troubleshoot.

**Comment by KenjiMinei** [comment]
![this](https://user-images.githubusercontent.com/62692574/149779021-a6d2f015-afd4-4477-8fce-901286d1fdde.png)

is correct? because with this change I didn't get an error output

**Comment by honoki** [comment]
Yes, that should be correct; except maybe the `ignore_ssl_errors` should have a lowercase `true`, I'm not sure.

**Comment by KenjiMinei** [comment]
Yes, I changed it to "true" and it returned error output

**Comment by KenjiMinei** [comment]
![outputerror](https://user-images.githubusercontent.com/62692574/149780513-6418bfbe-b0af-41a2-a6a2-670747c953da.png)

**Comment by KenjiMinei** [comment]
![thisouterror](https://user-images.githubusercontent.com/62692574/149780788-169002c7-d588-45ae-8202-2825d318c78a.png)

**Comment by KenjiMinei** [comment]
![erro5000](https://user-images.githubusercontent.com/62692574/149787819-9d349257-ace0-488e-9d80-e2dbb498220f.png)

this error gave when I disabled the debug
