### ISSUE TITLE
Add a command to return the infered program

### ISSUE THREAD

**Issue by aroly** [honoki/bbrf-client#95]
It would be nice to have a call which return the infered program when one submit, for example, a domain. 

This would allow to get the infered program name before triggering an action, and to store the results of this action (execute script, scan, cli...) in a specific location for arbitrary domains.

**Comment by aroly** [comment]
Workaround: `bbrf show $service | jq -r .program` works perfectly to get the program a service (or whatever) belongs to.

**Comment by honoki** [comment]
Hi @aroly - yeah, I would recommend using the workaround you suggested to make use of the power of the JSON db. :) Not planning to implement this as a BBRF command.

**Comment by aroly** [comment]
It makes sense, thanks for the feedback.
