### ISSUE TITLE
Error after install Client/server

### ISSUE THREAD

**Issue by rikosoo** [honoki/bbrf-client#99]
I play

bbrf new test

[ERROR] HTTPSConnectionPool(host='%3cyour-bbrf-server%3e', port=443): Max retries exceeded with url: /bbrf/test (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7feafb585c10>: Failed to establish a new connection: [Errno -2] Name or service not known'))

bbrf inscope add '*.af.mil' '*.osd.mil' '
[ERROR] You need to select a program to execute this action.

**Comment by rst10124492** [comment]
> Failed to establish a new connection: [Errno -2] Name or service not known'))

This is not an issue with bbrf, make sure to setup config.json with the correct details.

**Comment by honoki** [comment]
Please make sure to follow the setup instructions closely.
